import { MenuItem, SuiButton } from '@alextech9106/smooth-ui';
import { Component } from '@angular/core';
import { SuiButtonGroupComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-button-group/sui-button-group.component';
import { SuiButtonSplitComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-button-split/sui-button-split.component';
import { SuiButtonComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-button/sui-button.component';
import { SuiIconButtonComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-icon-button/sui-icon-button.component';
import { SuiIconComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-icon/sui-icon.component';
import { SuiLinkComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-link/sui-link.component';
import { SuiThemeToggleComponent } from '../../../../libs/smooth-ui/src/lib/components/sui-theme-toggle/sui-theme-toggle.component';

@Component({
  selector: 'app-root',
  imports: [
    SuiButtonComponent,
    SuiIconComponent,
    SuiIconButtonComponent,
    SuiButtonGroupComponent,
    SuiButtonSplitComponent,
    SuiLinkComponent,
    SuiThemeToggleComponent,
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  public icons: string[] = [
    'check',
    'x',
    'chevron-down',
    'chevron-up',
    'chevron-right',
    'chevron-left',
    'arrow-right',
    'arrow-left',
    'arrow-up',
    'arrow-down',
    'plus',
    'minus',
    'plus-circle',
    'minus-circle',
    'search',
    'info',
    'alert-triangle',
    'alert-circle',
    'check-circle',
    'x-circle',
    'star',
    'heart',
    'thumbs-up',
    'thumbs-down',
    'user',
    'settings',
    'bell',
    'calendar',
    'mail',
    'message-circle',
    'phone',
    'lock',
    'shield',
    'key',
    'eye',
    'eye-off',
    'trash',
    'edit',
    'save',
    'download',
    'upload',
    'undo',
    'redo',
    'refresh',
    'loader',
    'more-horizontal',
    'more-vertical',
    'filter',
    'external-link',
    'link',
    'share',
    'copy',
    'sun',
    'moon',
    'menu',
    'list',
    'home',
    'image',
    'camera',
    'play',
    'pause',
    'file',
    'folder',
    'bookmark',
    'tag',
    'credit-card',
    'shopping-cart',
    'gift',
    'map-pin',
    'globe',
    'grid',
    'circle',
    'square',
    'maximize',
    'minimize',
    'clock',
    'help',
    'log-out',
    'log-in',
  ];
  public buttonsGroup: SuiButton[] = [
    { name: 'Button 1', icon: 'check', selected: true },
    { name: 'Button 2', icon: 'x', selected: false },
    { name: 'Button 3', icon: 'star', selected: false },
  ];
  public menuItems: MenuItem[] = [
    { title: 'Item 1', icon: { name: 'check', size: 16 } },
    { title: 'Item 2', icon: { name: 'x', size: 16 }, separatorAfter: true },
    { title: 'Item 3', icon: { name: 'star', size: 16 } },
  ];
}
